### ISSUE TITLE
Might showing seconds on the clock be decoupled from showing the seconds ring?

### ISSUE THREAD

**Issue by JillSwift** [thevladsoft/Beclock-plasma6#1]
It would be nice to be able to see just HH:MM on the digital face and still have a seconds ring. 😸

**Comment by thevladsoft** [comment]
I think the problem was that if just HH:MM, the seconds ring would only update when the others ring did. Maybe there is some internal option that I have to change. Will check.

**Comment by thevladsoft** [comment]
Fixed in version 6.0-BE-2.1.

**Comment by JillSwift** [comment]
Dude, you are awesome 💖
